application: dlvritplus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /plusfeed\.png
  static_files: static/plusfeed.png
  upload: static/plusfeed\.png

- url: /style\.css
  static_files: static/style.css
  upload: static/style\.css

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /.*
  script: plusfeed.app
